# Generated by Django 5.1.1 on 2024-10-03 19:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanyTag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=255)),
                ("link", models.URLField()),
                ("problem_type", models.CharField(max_length=50)),
                ("last_reviewed", models.DateField(blank=True, null=True)),
                ("next_review", models.DateField(blank=True, null=True)),
                ("interval", models.IntegerField(default=1)),
                ("stability", models.FloatField(default=2.5)),
                ("difficulty", models.FloatField(default=5.0)),
                ("retention_factor", models.FloatField(default=0.8)),
                ("current_retention_rate", models.FloatField(blank=True, null=True)),
                ("feynman", models.TextField(blank=True)),
                ("average_time", models.FloatField(blank=True, null=True)),
                ("ratings", models.JSONField(blank=True, default=list)),
                ("solving_time", models.JSONField(blank=True, default=list)),
                (
                    "company_tags",
                    models.ManyToManyField(blank=True, to="core.companytag"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReviewSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("rating", models.IntegerField()),
                ("time_taken", models.FloatField()),
                ("explanation", models.TextField(blank=True)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="core.question"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_prep_mode", models.BooleanField(default=False)),
                ("company_prep_target", models.CharField(blank=True, max_length=100)),
                ("retention_factor", models.FloatField(default=0.8)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
