# Generated by Django 5.1.1 on 2024-10-06 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_question_average_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='problem_type',
            field=models.CharField(choices=[('Arrays', 'Arrays'), ('Hashing', 'Hashing'), ('2P', '2P'), ('Stack', 'Stack'), ('Sorting', 'Sorting'), ('Binary Search', 'Binary Search'), ('Sliding Window', 'Sliding Window'), ('Linked List', 'Linked List'), ('Greedy', 'Greedy'), ('Heap', 'Heap'), ('Intervals', 'Intervals'), ('Trees', 'Trees'), ('Math', 'Math'), ('Graphs', 'Graphs'), ('Backtracking', 'Backtracking'), ('Tries', 'Tries'), ('DP', 'DP')], max_length=50),
        ),
        migrations.AlterField(
            model_name='question',
            name='text',
            field=models.CharField(max_length=100),
        ),
    ]
